name: Run android regression tests
on:
  workflow_dispatch:
    inputs:
      tags:
        description: "APK.tar.gz url to test"
        required: true
        type: string
  # push:
  #   branches:
  #     - test-docker-container

jobs:
  android-regression:
    runs-on: [self-hosted, linux, x64, qa-android]
    steps:
      - name: run tests in already running container
        run: docker exec $(docker ps -q) sh -c "dl_and_test"
